base:
  build: base

squid:
  build: squid
  environment:
    DISK_CACHE_SIZE: 8000
    MAX_CACHE_OBJECT: 1000
    # SQUID_DIRECTIVES_ONLY: true
    # SQUID_DIRECTIVES: |
    #   refresh_pattern . 0 0 1 refresh-ims
  net: "host"
  privileged: true
  volumes:
    - "./volumes/var/cache/squid3/:/var/cache/squid3"

tproxy:
  build: iptables_auto_route
  net: "host"
  privileged: true
  links:
    - squid
